// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace AspNetCore7EFCoreDemo.Models;

public partial class Department
{
    public int DepartmentId { get; set; }

    public string Name { get; set; }

    public decimal Budget { get; set; }

    public DateTime StartDate { get; set; }

    public int? InstructorId { get; set; }

    [JsonIgnore]
    public byte[] RowVersion { get; set; }

    [JsonIgnore]
    public virtual ICollection<Course> Course { get; } = new List<Course>();

    [JsonIgnore]
    public virtual Person Instructor { get; set; }
}