// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspNetCore7EFCoreDemo.ViewModels;

public partial class CourseCreate
{
    public int CourseId { get; set; }

    public string Title { get; set; }

    public int DepartmentId { get; set; }
}