// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AspNetCore7EFCoreDemo.Models
{
    public partial class Department_UpdateResult
    {
        public byte[] RowVersion { get; set; }
    }
}
